-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 1
-- Name:    8 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 1.

CREATE TABLE IF NOT EXISTS "admin_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "display_name" TEXT,
  "role" TEXT NOT NULL DEFAULT 'read_only',
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "admin_profiles_user_id_unique" UNIQUE ("user_id")
);

CREATE TABLE IF NOT EXISTS "deposit_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reference_number" TEXT NOT NULL,
  "customer_name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "business_name" TEXT,
  "number_of_users" TEXT,
  "selected_service" TEXT NOT NULL,
  "service_id" TEXT NOT NULL,
  "business_needs" TEXT,
  "full_service_price_cents" INTEGER NOT NULL,
  "deposit_paid_cents" INTEGER NOT NULL,
  "remaining_balance_cents" INTEGER NOT NULL,
  "stripe_payment_id" TEXT,
  "checkout_session_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'deposit_paid',
  "sales_email_sent" BOOLEAN NOT NULL DEFAULT false,
  "customer_email_sent" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "deposit_requests_checkout_session_id_unique" UNIQUE ("checkout_session_id"),
  CONSTRAINT "deposit_requests_reference_number_unique" UNIQUE ("reference_number")
);

CREATE TABLE IF NOT EXISTS "internal_notes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "note" TEXT NOT NULL,
  "created_by" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "order_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "previous_status" TEXT,
  "new_status" TEXT NOT NULL,
  "note" TEXT,
  "changed_by" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "public_id" TEXT NOT NULL,
  "purchase_id" TEXT NOT NULL,
  "stripe_checkout_session_id" TEXT NOT NULL,
  "stripe_payment_intent_id" TEXT,
  "customer_name" TEXT NOT NULL,
  "customer_email" TEXT NOT NULL,
  "customer_phone" TEXT,
  "customer_company" TEXT,
  "customer_domain" TEXT,
  "number_of_users" TEXT,
  "business_needs" TEXT,
  "service_id" TEXT NOT NULL,
  "service_name" TEXT NOT NULL,
  "package_name" TEXT NOT NULL,
  "total_service_price_cents" INTEGER NOT NULL,
  "deposit_amount_paid_cents" INTEGER NOT NULL,
  "remaining_balance_cents" INTEGER NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "payment_status" TEXT NOT NULL DEFAULT 'Deposit Paid',
  "project_status" TEXT NOT NULL DEFAULT 'Deposit Received',
  "appdirect_quote_status" TEXT NOT NULL DEFAULT 'Not Started',
  "devs_ai_quote_status" TEXT NOT NULL DEFAULT 'Pending Review',
  "appdirect_quote_sent_at" TIMESTAMPTZ,
  "appdirect_subscription_activated_at" TIMESTAMPTZ,
  "remaining_balance_paid_at" TIMESTAMPTZ,
  "expected_start_date" TEXT,
  "expected_completion_date" TEXT,
  "stripe_receipt_url" TEXT,
  "devs_ai_subscription_included" BOOLEAN NOT NULL DEFAULT false,
  "custom_ai_agent_included" BOOLEAN NOT NULL DEFAULT false,
  "google_workspace_included" BOOLEAN NOT NULL DEFAULT false,
  "third_party_costs_included" BOOLEAN NOT NULL DEFAULT false,
  "assigned_admin_id" TEXT,
  "sales_email_sent" BOOLEAN NOT NULL DEFAULT false,
  "customer_email_sent" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "orders_public_id_unique" UNIQUE ("public_id"),
  CONSTRAINT "orders_purchase_id_unique" UNIQUE ("purchase_id"),
  CONSTRAINT "orders_stripe_checkout_session_id_unique" UNIQUE ("stripe_checkout_session_id")
);

CREATE TABLE IF NOT EXISTS "phone_verify_attempts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "purchase_id" TEXT NOT NULL,
  "ip_hash" TEXT,
  "success" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "purchase_id_counters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "year" TEXT NOT NULL,
  "last_seq" INTEGER NOT NULL DEFAULT 0,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "purchase_id_counters_year_unique" UNIQUE ("year")
);

CREATE OR REPLACE FUNCTION "next_purchase_id"()
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
AS $appbuilder_pgfn$
    DECLARE
      y text := to_char((NOW() AT TIME ZONE 'UTC'), 'YYYY');
      n integer;
    BEGIN
      INSERT INTO purchase_id_counters (year, last_seq, updated_at)
      VALUES (y, 1, NOW())
      ON CONFLICT (year) DO UPDATE
        SET last_seq = purchase_id_counters.last_seq + 1,
            updated_at = NOW()
      RETURNING last_seq INTO n;
      RETURN 'AON-' || y || '-' || lpad(n::text, 6, '0');
    END;
  $appbuilder_pgfn$;
COMMENT ON FUNCTION "next_purchase_id"() IS 'managed-by:devs-ai';
