-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 2
-- Name:    6 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 2.

CREATE TABLE IF NOT EXISTS "agreement_id_counters" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "year" TEXT NOT NULL,
  "last_seq" INTEGER NOT NULL DEFAULT 0,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "agreement_id_counters_year_unique" UNIQUE ("year")
);

CREATE TABLE IF NOT EXISTS "cookie_consents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consent_id" TEXT NOT NULL,
  "essential" BOOLEAN NOT NULL DEFAULT true,
  "functional" BOOLEAN NOT NULL DEFAULT false,
  "analytics" BOOLEAN NOT NULL DEFAULT false,
  "marketing" BOOLEAN NOT NULL DEFAULT false,
  "consent_version" TEXT NOT NULL DEFAULT 1.0,
  "ip_hash" TEXT,
  "user_agent" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "cookie_consents_consent_id_unique" UNIQUE ("consent_id")
);

CREATE TABLE IF NOT EXISTS "customer_agreements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "public_id" TEXT NOT NULL,
  "agreement_reference" TEXT NOT NULL,
  "purchase_id" TEXT,
  "customer_name" TEXT NOT NULL,
  "business_name" TEXT,
  "customer_title" TEXT,
  "customer_email" TEXT NOT NULL,
  "customer_phone" TEXT,
  "customer_domain" TEXT,
  "package_id" TEXT NOT NULL,
  "package_name" TEXT NOT NULL,
  "service_name" TEXT NOT NULL,
  "deliverables_snapshot" TEXT NOT NULL,
  "exclusions_snapshot" TEXT NOT NULL,
  "customer_responsibilities_snapshot" TEXT NOT NULL,
  "timeline_snapshot" TEXT NOT NULL,
  "total_service_price_cents" INTEGER NOT NULL,
  "deposit_amount_cents" INTEGER NOT NULL,
  "amount_paid_today_cents" INTEGER NOT NULL,
  "remaining_balance_cents" INTEGER NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'USD',
  "refund_summary_snapshot" TEXT NOT NULL,
  "third_party_cost_summary_snapshot" TEXT NOT NULL,
  "accepted_document_versions" TEXT NOT NULL,
  "accepted_document_hashes" TEXT NOT NULL,
  "full_agreement_snapshot" TEXT NOT NULL,
  "electronic_signature" TEXT NOT NULL,
  "electronic_signature_consent_text" TEXT NOT NULL,
  "accepted_at" TIMESTAMPTZ DEFAULT now(),
  "signature_date" TEXT NOT NULL,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "stripe_checkout_session_id" TEXT,
  "stripe_payment_intent_id" TEXT,
  "payment_status" TEXT NOT NULL DEFAULT 'pending',
  "agreement_status" TEXT NOT NULL DEFAULT 'accepted_pending_payment',
  "confirmation_email_sent" BOOLEAN NOT NULL DEFAULT false,
  "confirmation_email_sent_at" TIMESTAMPTZ,
  "marketing_opt_in" BOOLEAN NOT NULL DEFAULT false,
  "checkbox_order_review" BOOLEAN NOT NULL DEFAULT false,
  "checkbox_third_party" BOOLEAN NOT NULL DEFAULT false,
  "checkbox_legal_policies" BOOLEAN NOT NULL DEFAULT false,
  "checkbox_esign" BOOLEAN NOT NULL DEFAULT false,
  "business_needs" TEXT,
  "number_of_users" TEXT,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "customer_agreements_agreement_reference_unique" UNIQUE ("agreement_reference"),
  CONSTRAINT "customer_agreements_public_id_unique" UNIQUE ("public_id")
);

CREATE TABLE IF NOT EXISTS "legal_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "document_type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "version" TEXT NOT NULL,
  "effective_at" TEXT NOT NULL,
  "published_at" TEXT,
  "content_html" TEXT NOT NULL,
  "content_text" TEXT NOT NULL,
  "content_hash" TEXT NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ DEFAULT now(),
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "legal_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "setting_key" TEXT NOT NULL,
  "setting_value" TEXT,
  "is_placeholder" BOOLEAN NOT NULL DEFAULT true,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "legal_settings_setting_key_unique" UNIQUE ("setting_key")
);

CREATE OR REPLACE FUNCTION "next_agreement_id"()
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
AS $appbuilder_pgfn$
    DECLARE
      y text := to_char((NOW() AT TIME ZONE 'UTC'), 'YYYY');
      n integer;
    BEGIN
      INSERT INTO agreement_id_counters (year, last_seq, updated_at)
      VALUES (y, 1, NOW())
      ON CONFLICT (year) DO UPDATE
        SET last_seq = agreement_id_counters.last_seq + 1,
            updated_at = NOW()
      RETURNING last_seq INTO n;
      RETURN 'AGR-' || y || '-' || lpad(n::text, 6, '0');
    END;
  $appbuilder_pgfn$;
COMMENT ON FUNCTION "next_agreement_id"() IS 'managed-by:devs-ai';
