-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 3
-- Name:    5 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 3.

ALTER TABLE "customer_agreements" ADD COLUMN IF NOT EXISTS "access_token" TEXT;

ALTER TABLE "customer_agreements" ADD COLUMN IF NOT EXISTS "auth_user_id" TEXT;

ALTER TABLE "deposit_requests" ADD COLUMN IF NOT EXISTS "auth_user_id" TEXT;

ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "auth_user_id" TEXT;

ALTER TABLE "customer_agreements" ADD CONSTRAINT "customer_agreements_access_token_unique" UNIQUE ("access_token");
